### ISSUE TITLE
Config reading type error

### ISSUE THREAD

**Issue by bobtfish** [bobtfish/AWSnycast#2]
INFO[0000] Got instance metadata                         availability_zone=us-west-1a instance_id=i-a9966cf5 region=us-west-1 subnet_id=subnet-db2dd0b3
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
github.com/bobtfish/AWSnycast/config.func·001(0x0, 0xc2081a7478, 0x6, 0x1, 0xc2081cd8f0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/config/route_find.go:33 +0x662
github.com/bobtfish/AWSnycast/config.RouteTableFindSpec.GetFilter(0x0, 0xc2081a7478, 0x6, 0x1, 0xc2081cd8f0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/config/route_find.go:114 +0xb7
github.com/bobtfish/AWSnycast/config.getFiltersListForSpec(0x1, 0xc20800aee8, 0x3, 0x0, 0xc20803bb00, 0x0, 0x0, 0x0, 0x1)
	/go/src/github.com/bobtfish/AWSnycast/config/route_find.go:101 +0x711
github.com/bobtfish/AWSnycast/config.func·002(0x1, 0xc20800aee8, 0x3, 0x0, 0xc20803bb00, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/config/route_find.go:39 +0x69
github.com/bobtfish/AWSnycast/config.RouteTableFindSpec.GetFilter(0x1, 0xc20800aee8, 0x3, 0x0, 0xc20803bb00, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/config/route_find.go:114 +0xb7
github.com/bobtfish/AWSnycast/config.(*RouteTable).UpdateEc2RouteTables(0xc2080bb080, 0xc208206210, 0x6, 0x6, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/config/config.go:30 +0x60
github.com/bobtfish/AWSnycast/daemon.(*Daemon).RunOneRouteTable(0xc20806c0b0, 0xc208206210, 0x6, 0x6, 0xc20800aea0, 0x9, 0xc2080bb080, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/daemon/daemon.go:88 +0x5e
github.com/bobtfish/AWSnycast/daemon.(*Daemon).RunRouteTables(0xc20806c0b0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/daemon/daemon.go:100 +0x18d
github.com/bobtfish/AWSnycast/daemon.(*Daemon).Run(0xc20806c0b0, 0x9b0000, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/daemon/daemon.go:121 +0x4fa
main.main()
	/go/src/github.com/bobtfish/AWSnycast/main.go:40 +0x2a1

goroutine 34 [runnable]:
net/http.(*persistConn).readLoop(0xc20806c630)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 35 [select]:
net/http.(*persistConn).writeLoop(0xc20806c630)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 33 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

**Comment by bobtfish** [comment]
NFO[0000] Got instance metadata                         availability_zone=us-west-2b instance_id=i-ec4d57e1 region=us-west-2 subnet_id=subnet-9c33deeb
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
github.com/bobtfish/AWSnycast/config.func·001(0x0, 0xc2082dd520, 0x6, 0x1, 0xc2082ce9f0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/config/route_find.go:33 +0x662
github.com/bobtfish/AWSnycast/config.RouteTableFindSpec.GetFilter(0x0, 0xc2082dd520, 0x6, 0x1, 0xc2082ce9f0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/config/route_find.go:114 +0xb7
github.com/bobtfish/AWSnycast/config.getFiltersListForSpec(0x1, 0xc20800aef8, 0x3, 0x0, 0xc20803bb00, 0x0, 0x0, 0x0, 0x1)
	/go/src/github.com/bobtfish/AWSnycast/config/route_find.go:101 +0x711
github.com/bobtfish/AWSnycast/config.func·002(0x1, 0xc20800aef8, 0x3, 0x0, 0xc20803bb00, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/config/route_find.go:39 +0x69
github.com/bobtfish/AWSnycast/config.RouteTableFindSpec.GetFilter(0x1, 0xc20800aef8, 0x3, 0x0, 0xc20803bb00, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/config/route_find.go:114 +0xb7
github.com/bobtfish/AWSnycast/config.(*RouteTable).UpdateEc2RouteTables(0xc2080bee40, 0xc20828d740, 0x18, 0x18, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/config/config.go:30 +0x60
github.com/bobtfish/AWSnycast/daemon.(*Daemon).RunOneRouteTable(0xc20806c0b0, 0xc20828d740, 0x18, 0x18, 0xc20800aeb0, 0x9, 0xc2080bee40, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/daemon/daemon.go:88 +0x5e
github.com/bobtfish/AWSnycast/daemon.(*Daemon).RunRouteTables(0xc20806c0b0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/daemon/daemon.go:100 +0x18d
github.com/bobtfish/AWSnycast/daemon.(*Daemon).Run(0xc20806c0b0, 0x9b0000, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/daemon/daemon.go:121 +0x4fa
main.main()
	/go/src/github.com/bobtfish/AWSnycast/main.go:40 +0x2a1

goroutine 34 [IO wait]:
net.(*pollDesc).Wait(0xc208010df0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010df0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010d90, 0xc208221800, 0x400, 0x400, 0x0, 0x7f27ec37ba48, 0xc20807d970)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080380b0, 0xc208221800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc208251bf0, 0x7f27ec37d348, 0xc2080380b0, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208077080, 0x17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208077080, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f27ec3825d8, 0xc208077080, 0xc20806c688, 0xc20800f000, 0x1000, 0x1000, 0x84d8e0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2082800a0, 0xc20800f000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2080410e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2080410e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20806c630)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 35 [select]:
net/http.(*persistConn).writeLoop(0xc20806c630)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 33 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

**Comment by bobtfish** [comment]
NFO[0000] Got instance metadata                         availability_zone=us-west-1b instance_id=i-e19ed853 region=us-west-1 subnet_id=subnet-28b0e940
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x57fd09]

goroutine 1 [running]:
github.com/bobtfish/AWSnycast/aws.findRouteFromRouteTable(0xc20820e100, 0x3, 0x3, 0xc2080387c8, 0x1, 0x1, 0xc2081f6258, 0xc2080e0300, 0x8, 0x8, ...)
	/go/src/github.com/bobtfish/AWSnycast/aws/aws.go:257 +0x109
github.com/bobtfish/AWSnycast/aws.RouteTableManagerEC2.ManageInstanceRoute(0x0, 0x0, 0x7f73d300d878, 0xc208038178, 0xc20820e100, 0x3, 0x3, 0xc2080387c8, 0x1, 0x1, ...)
	/go/src/github.com/bobtfish/AWSnycast/aws/aws.go:212 +0x70
github.com/bobtfish/AWSnycast/aws.(*RouteTableManagerEC2).ManageInstanceRoute(0xc20801f8e0, 0xc20820e100, 0x3, 0x3, 0xc2080387c8, 0x1, 0x1, 0xc2081f6258, 0xc2080e0300, 0x8, ...)
	<autogenerated>:11 +0x10e
github.com/bobtfish/AWSnycast/config.(*RouteTable).RunEc2Updates(0xc208090de0, 0x7f73d300d8c8, 0xc20801f8e0, 0x0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/config/config.go:55 +0x53c
github.com/bobtfish/AWSnycast/daemon.(*Daemon).RunOneRouteTable(0xc20806c0b0, 0xc20824da10, 0x5, 0x5, 0xc20800aaf0, 0x6, 0xc208090de0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/daemon/daemon.go:91 +0xbf
github.com/bobtfish/AWSnycast/daemon.(*Daemon).RunRouteTables(0xc20806c0b0, 0x0, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/daemon/daemon.go:100 +0x18d
github.com/bobtfish/AWSnycast/daemon.(*Daemon).Run(0xc20806c0b0, 0x9b0000, 0x0)
	/go/src/github.com/bobtfish/AWSnycast/daemon/daemon.go:121 +0x4fa
main.main()
	/go/src/github.com/bobtfish/AWSnycast/main.go:40 +0x2a1

goroutine 34 [runnable]:
net/http.(*persistConn).readLoop(0xc20806c630)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 35 [select]:
net/http.(*persistConn).writeLoop(0xc20806c630)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 33 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
